### ISSUE TITLE
All the videos in the Documentation section returns a 404. Permission issue ?

### ISSUE THREAD

**Issue by abeshbh** [SAP/migration-tool-for-cloud-integration#24]
Page : https://github.com/SAP/migration-tool-for-cloud-integration/tree/main/docs
All the videos on that page return a 404. Guessing a permission issue.

Also is this tool still relevant for doing Integration Suite Migrations ?

**Comment by willemi069808** [comment]
Hi Abesh,

Yes absolutely the tool is still there to use.
The video's work fine on my side, so maybe try to clear cache and reload?

Thanks
Willem

**Comment by abeshbh** [comment]
Thanks so much for your wonderful tool Willem ! Going to use it in a live migration project, fingers crossed :)
It was indeed a cache issue on my side. Hard reload fixed it.

**Comment by willemi069808** [comment]
Interested to learn from your experience - or if there is anything I can help or validate - happy to discuss via MS Teams (willem.pardaens -at- sap.com).
